server:
  port: 80


logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
    reactor:
      netty:
        channel: DEBUG


spring:
  application:
    name: control-gateway

  cloud:

    load-balance:
      ribbon:
        enable: false

    gateway:
      metrics:
        enable: true
      discovery:
        locator:
          enable: true
          lower-case-service-id: true

      routes:
        - id: main
          uri: https://github.com/
          predicates:
            - Path=/
            - Method=GET

        - id: test
          uri: https://github.com/
          predicates:
            - Path=/test
            - Method=GET

        # brand

        - id: createBrand
          uri: lb://service-brand
          predicates:
            - Path=/brand
            - Method=POST

        - id: updateBrand
          uri: lb://service-brand
          predicates:
            - Path=/brand
            - Method=PUT

        - id: deleteBrand
          uri: lb://service-brand
          predicates:
            - Path=/brand/{id}
            - Method=DELETE

        - id: getBrands
          uri: lb://service-brand
          predicates:
            - Path=/brand
            - Method=GET

        - id: getBrandByID
          uri: lb://service-brand
          predicates:
            - Path=/brand/{id}
            - Method=GET

        # category

        - id: createCategory
          uri: lb://service-category
          predicates:
            - Path=/category
            - Method=POST

        - id: updateCategory
          uri: lb://service-category
          predicates:
            - Path=/category
            - Method=PUT

        - id: deleteCategory
          uri: lb://service-category
          predicates:
            - Path=/category/{id}
            - Method=DELETE

        - id: getCategories
          uri: lb://service-category
          predicates:
            - Path=/category
            - Method=GET

        - id: getCategoryByID
          uri: lb://service-category
          predicates:
            - Path=/category/{id}
            - Method=GET

        # product

        - id: createProduct
          uri: lb://service-product
          predicates:
            - Path=/product
            - Method=POST

        - id: updateProduct
          uri: lb://service-product
          predicates:
            - Path=/product
            - Method=PUT

        - id: deleteProduct
          uri: lb://service-product
          predicates:
            - Path=/product/{id}
            - Method=DELETE

        - id: getProducts
          uri: lb://service-product
          predicates:
            - Path=/product
            - Method=GET

        - id: getProductByID
          uri: lb://service-product
          predicates:
            - Path=/product/{id}
            - Method=GET

        # search

        - id: search
          uri: lb://service-search
          predicates:
            - Path=/search/{term}
            - Method=GET

        # shopping-car

        - id: addToShoppingCar
          uri: lb://service-shopping-car
          predicates:
            - Path=/shopping-car
            - Method=POST

        - id: deleteToShoppingCar
          uri: lb://service-shopping-car
          predicates:
            - Path=/shopping-car
            - Method=DELETE

        - id: getAllToShoppingCar
          uri: lb://service-shopping-car
          predicates:
            - Path=/shopping-car
            - Method=GET


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
#    service-url:
#      defaultZone: http://control-discovery:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - gateway
    info:
      enabled: true
    health:
      enabled: true
    gateway:
      enable: true