server:
  port: 80


logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
    reactor:
      netty:
        channel: DEBUG


spring:
  application:
    name: control-gateway

  cloud:

    load-balance:
      ribbon:
        enable: false

    gateway:
      metrics:
        enable: true
      discovery:
        locator:
          enable: true
          lower-case-service-id: true

      routes:
        - id: main
          uri: https://github.com/
          predicates:
            - Path=/
            - Method=GET

        - id: ping
          uri: lb://control-identity
          predicates:
            - Path=/ping
            - Method=GET

        - id: test
          uri: https://github.com/
          predicates:
            - Path=/test
            - Method=GET


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
#    service-url:
#      defaultZone: http://control-discovery:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - gateway
    info:
      enabled: true
    health:
      enabled: true
    gateway:
      enable: true