server:
  port: 9001

spring:

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/e-commerce
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1;
      connection-timeout: 20000

  application:
    name: service-search

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 0
      location: /tmp

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
#    service-url:
#      defaultZone: http://control-discovery:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - gateway
    info:
      enabled: true
    health:
      enabled: true
    gateway:
      enable: true
